CH1_Q = [
    input("Provides connectivity and ensures data flow across the network:\n"),
    input("Runs over telephone line:\n"),
    input("Media in which data is encoded into electrical impulses that travel through metal wires within cables:\n"),
    input("A computer that functions both as the client and the server on a network:\n"),
    input("ICANN:\n"),
    input("Internet access for areas with no internet:\n"),
    input("Use dest. end device address in conjunction with info. about the network interconnection to determine msg. paths through a network:\n"),
    input("Provides high-speed bandwidth to internal end devices and intermediary devices:\n"),
    input("Provides the channel over which the message travels from source to destination:\n"),
    input("Logical/Hierarchical name identifier:\n"),
    input("Data encoded via modulation of specific frequencies of electromagnetic waves:\n"),
    input("High bandwidth, high availability, always-on connection to the internet:\n"),
    input("Low bandwidth; any phone line + modem:\n"),
    input("What is a network infrastructure that spans a small geographical area.\n"),
    input("Illustrates devices, ports, and the addressing scheme of the network:\n"),
    input("A device on a network identified by an IP Address:\n"),
    input("What devices connect the individual end devices to the network?\n"),
    input("Worldwide collection of interconnected networks:\n"),
    input("IAB:\n"),
    input("Glass or plastic fibers within cables:\n"),
    input("What is either the source or destination of a message transmitted over the network?\n"),
    input("IETF:\n"),
    input("Mandatory documentation for a network. Visual map of networks:\n"),
    input("DSL:\n"),
    input('Reserved circuits within the service provider\'s network that connect geographically separated offices for private voice and/or data networking. The circuits are rented at a monthly or yearly rate:\n'),
    input("Physically connects end devices to the network:\n"),
    input("Specialized ports on networking devices that connect individual networks:\n"),
    input("Confidentiality, integrity, and availability are requirements of which of the four basic characteristics of network architecture?:\n"),
    input("Safe/secure access to outsiders from organizations; suppliers,contractors:\n"),
    input("Typically provide slower speed links between LANs:\n"),
    input("Connector, outlet on a networking device where the media connects either to an end device, or another networking device:\n"),
    input("Illustrates the cable and hardware setup between intermediary and end devices:\n"),
    input("Provides uploads and downloads at the same high speeds:\n"),
    input("Private connection of LANs and WANs; belongs to an organization:\n"),
    input("In context, refers to the technologies that support the infrastructure & programmed services/rules/protocols, that move data across the network:\n"),
    input("Limits the number of affected devices during network failure.\n"),
    input("Built for quick recovery; multi-path dependence between destination and source:\n"),
    input("Data traveling through different paths but to the same destination:\n"),
    input("Bandwidth demand exceeds available amount; bps:\n"),
    input("Assures safe information transmission from source to destination:\n"),
    input("Physical/Flat Unique Identifier:\n"),
    input("Which topology does Ethernet belong to?\n"),
    input("Timely reliable data access:\n"),
    input("Only intended and authorized recipients can access data:\n"),
    input("CCNA:\n"),
    input("NAT:\n"),
    input("Sometimes known as Ethernet WAN, extend LAN access technology into the WAN.:\n"),
    input("FDDI:\n"),
    input("Which attack slows down or crashes equipment and programs?\n"),
    input("What network creates a secure connection for remote workers?\n"),
    input("What software blocks unauthorized access to your network?\n"),
    input("What describes a network attack that occurs on the first day that a vulnerability becomes known?\n"),
    input("What describes malicious code running on user devices?\n")
]
# CH3_Q = []
# CH2_Q = []
# CH4_Q = []

CH1_A = [
    "Intermediary Device",
    "DSL",
    "Copper",
    "Peer-to-Peer",
    "Internet Corporation for Assigned Names and Numbers",
    "Satellite",
    "Intermediary Device",
    "LAN",
    "Media",
    "IP Address",
    "Wireless",
    "DSL",
    "Dial-Up Telephone",
    "LAN",
    "Logical Topology Diagram",
    "End Device",
    "Intermediary Device",
    "The Internet",
    "Internet Architecture Board",
    "Fiber-Optic",
    "End Device",
    "Internet Engineering Task Force",
    "Topology Diagram",
    "Digital Subscriber Line",
    "Dedicated Leased Line",
    "NIC",
    "Interface",
    "QoS",
    "Extranet",
    "WAN",
    "Port",
    "Physical Topology Diagram",
    "Symmetric Digital Subscriber Line",
    "Intranet",
    "Network Architecture",
    "Fault Tolerance",
    "Redundancy",
    "Packet Switching",
    "Congestion",
    "Integrity",
    "MAC Address",
    "Physical",
    "Availability",
    "Confidentiality",
    "Cisco Certified Network Administration",
    "Network Address Translation",
    "Metro Ethernet",
    "Fiber Data Distributed Interface",
    "Denial of Service",
    "Virtual Private Network",
    "Firewall",
    "Zero-Day or Zero-Hour",
    "Virus, Worm, or Trojan"
]
# CH3_A = []
# CH2_A = []
# CH4_A = []
