# CH1_Q = [
#     input("Provides connectivity and ensures data flow across the network:\n"),
#     input("Runs over telephone line:\n"),
#     input("Media in which data is encoded into electrical impulses that travel through metal wires within cables:\n"),
#     input("A computer that functions both as the client and the server on a network:\n"),
#     input("ICANN:\n"),
#     input("Internet access for areas with no internet:\n"),
#     input("Use dest. end device address in conjunction with info. about the network interconnection to determine msg. paths through a network:\n"),
#     input("Provides high-speed bandwidth to internal end devices and intermediary devices:\n"),
#     input("Provides the channel over which the message travels from source to destination:\n"),
#     input("Logical/Hierarchical name identifier:\n"),
#     input("Data encoded via modulation of specific frequencies of electromagnetic waves:\n"),
#     input("High bandwidth, high availability, always-on connection to the internet:\n"),
#     input("Low bandwidth; any phone line + modem:\n"),
#     input("What is a network infrastructure that spans a small geographical area.\n"),
#     input("Illustrates devices, ports, and the addressing scheme of the network:\n"),
#     input("A device on a network identified by an IP Address:\n"),
#     input("What devices connect the individual end devices to the network?\n"),
#     input("Worldwide collection of interconnected networks:\n"),
#     input("IAB:\n"),
#     input("Glass or plastic fibers within cables:\n"),
#     input("What is either the source or destination of a message transmitted over the network?\n"),
#     input("IETF:\n"),
#     input("Mandatory documentation for a network. Visual map of networks:\n"),
#     input("DSL:\n"),
#     input('Reserved circuits within the service provider\'s network that connect geographically separated offices for private voice and/or data networking. The circuits are rented at a monthly or yearly rate:\n'),
#     input("Physically connects end devices to the network:\n"),
#     input("Specialized ports on networking devices that connect individual networks:\n"),
#     input("Confidentiality, integrity, and availability are requirements of which of the four basic characteristics of network architecture?:\n"),
#     input("Safe/secure access to outsiders from organizations; suppliers,contractors:\n"),
#     input("Typically provide slower speed links between LANs:\n"),
#     input("Connector, outlet on a networking device where the media connects either to an end device, or another networking device:\n"),
#     input("Illustrates the cable and hardware setup between intermediary and end devices:\n"),
#     input("Provides uploads and downloads at the same high speeds:\n"),
#     input("Private connection of LANs and WANs; belongs to an organization:\n"),
#     input("In context, refers to the technologies that support the infrastructure & programmed services/rules/protocols, that move data across the network:\n"),
#     input("Limits the number of affected devices during network failure.\n"),
#     input("Built for quick recovery; multi-path dependence between destination and source:\n"),
#     input("Data traveling through different paths but to the same destination:\n"),
#     input("Bandwidth demand exceeds available amount; bps:\n"),
#     input("Assures safe information transmission from source to destination:\n"),
#     input("Physical/Flat Unique Identifier:\n"),
#     input("Which topology does Ethernet belong to?\n"),
#     input("Timely reliable data access:\n"),
#     input("Only intended and authorized recipients can access data:\n"),
#     input("CCNA:\n"),
#     input("NAT:\n"),
#     input("Sometimes known as Ethernet WAN, extend LAN access technology into the WAN.:\n"),
#     input("FDDI:\n"),
#     input("Which attack slows down or crashes equipment and programs?\n"),
#     input("What network creates a secure connection for remote workers?\n"),
#     input("What software blocks unauthorized access to your network?\n"),
#     input("What describes a network attack that occurs on the first day that a vulnerability becomes known?\n"),
#     input("What describes malicious code running on user devices?\n")
# ]
# CH3_Q = [
#     input("Enables 2 or more devices to communicate over 1 or more networks; IP, TCP, HTTP:\n"),
#     input("Data authentication, integrity, encryption; SSH, SSL, TLS:\n"),
#     input("Routers exchange route information, compare route information; best path to dest. network. OSPF, BGP:\n"),
#     input("Automatic detection of devices or services; DHCP service discovery for IP Address allocation; DNS:\n"),
#     input("Group of interrelated protocols necessary to perform a communication function:\n"),
#     input("SLAAC:\n"),
#     input("Translates domain names into IP Addresses:\n"),
#     input("Dynamically assigns IPv4 addressing info. to clients at the startup and allows the addresses to be reused when no longer needed:\n"),
#     input("A method that allows a device to obtain IPv6 addressing info. without a DHCPv6 server:\n"),
#     input("Enables clients to send email to a mail server and enables servers to send email to other servers:\n"),
#     input("Enables clients to retrieve email from a mail server and download the email to the client's local mail app:\n"),
#     input("Enables clients to access email stored on a mail server as well as maintaining email on the server:\n"),
#     input("Sets the rules that enable a user on one host to access and transfer files to and from another host over a network; reliable, connection-oriented, and acknowledged delivery protocol:\n"),
#     input("An extension of Secure Shell Protocol; can be used to establish secure file transfer sessions in which file transfer is encrypted. SSH is a method for secure remote login that is typically used for accessing the CLI of a device:\n"),
#     input("Simple, connection-less file transfer protocol with best-effort, unacknowledged file delivery; less overhead than FTP:\n"),
#     input("A set of rules for exchanging text in, graphic images, sound, video, and other multimedia files on the World Wide Web:\n"),
#     input("Encrypts the data that is exchanged over the WWW:\n"),
#     input("A web service that uses application programming interfaces (APIs) and HTTP requests to create web applications:\n"),
#     input("Enables reliable communication between processes running on separate hosts and provides reliable, acknowledged transmissions that confirm successful delivery:\n"),
#     input("Enables a process on one host to send packets to a process on another host; does not confirm successful datagram transmission:\n"),
#     input("Receives message segments from the transport layer, packages messages into packets, and addresses packets for end-to-end delivery over a network. uses 32 bit address:\n"),
#     input("Uses 128 bit address:\n"),
#     input("Translates IPv4 addresses from a private network into globally unique public IPv4 addresses:\n"),
#     input("Provides feedback from destination host to a source host about errors in packet delivery:\n"),
#     input("Includes four protocol messages that are used for address resolution and duplicate address detection:\n"),
#     input("Link-state routing protocol that uses a hierarchical design based on areas; open standard interior routing protocol:\n"),
#     input("An open standard routing protocol developed by CISCO that uses a composite metric based on bandwidth, delay, load, and reliability:\n"),
#     input("An open standard exterior gateway routing protocol used between ISPs; commonly between ISPs and their large private clients to exchange routing info:\n"),
#     input("Provides dynamic address mapping between an IPv4 address and a hardware address:\n"),
#     input("Defines rules for wiring and signaling standards on the network access layer:\n"),
#     input("Defines rules for wireless signaling across the 2.4GHz and 5GHz radio frequencies:\n"),
#     input("MAC:\n"),
#     input("MAC Addresses are physically embedded on the Ethernet:\n"),
#     input("Data Link address, or the Ethernet address of the device that sends the data link frame from the encapsulated IP packet:\n"),
#     input("When the receiving device is on the same network as the sending device, this is the data link address of the receiving device:\n"),
#     input("SSL:\n"),
#     input("TLS:\n"),
#     input("Data authentication, integrity, encryption (Full Name):\n")
# ]
# CH2_Q = [
#     input("UI that allows users to request specific tasks on PC; can be done through CLI or GUI interfaces:\n"),
#     input("Communicates between the hardware and software of a computer; manages how hardware is used to meet software requirements:\n"),
#     input("Physical part of a computer including underlying electronics:\n"),
#     input("The family of network operating systems used on many Cisco devices:\n"),
#     input("The operating system on home routers:\n"),
#     input("In-band and recommended method for remotely establishing a secure CLI connection, through a virtual interface, over a network:\n"),
#     input("Physical management port that provides out-of-band access to a Cisco device:\n"),
#     input("Insecure, in-band method of remotely establishing a CLI session, through a virtual interface, over a network:\n"),
#     input("What access method would be most appropriate if you were in the equipment room with a new switch that needs to be configured?\n"),
#     input("What access method would be the most appropriate in-band access to the IOS over a network connection?\n"),
#     input("What access method would be the most appropriate if you call your manager to tell him you cannot access your router in another city over the internet and he provides you with the information to access the router through a telephone connection?\n"),
#     input("This mode has limited capabilities but is useful for basic operations. It allows only a limited number of basic monitoring commands but does not allow the execution of any commands that might change the configuration of the device:\n"),
#     input("To execute configuration commands, a network administrator must access this mode; Higher configuration modes, like global configuration mode, can only be reached:\n"),
#     input("What symbol does User EXEC Mode end with?\n"),
#     input("What symbol does Privileged EXEC Mode end with?\n"),
#     input("Mode used to configure console, SSH, Telnet, or AUX access:\n"),
#     input("Mode used to configure a switch port or router network interface:\n"),
#     input("What command changes the name of the router?\n"),
#     input("What command sets router name to default?\n"),
#     input("What command encrypts all plaintext passwords?\n"),
#     input("Line that enables remote access using Telnet or SSH to the device:\n"),
#     input("What command secures User EXEC Mode?\n"),
#     input("What command verifies password encryption?\n"),
#     input("Which command configures the message of the day?\n"),
#     input("This is the saved configuration file that is stored in NVRAM. It contains all the commands that will be used by the device upon startup or reboot:\n"),
#     input("Does not lose its contents when the device is powered off:\n"),
#     input("This is stored in Random Access Memory (RAM). It reflects the current configuration; modification affects the operation of a Cisco device immediately. RAM is volatile memory. It loses all of its content when the device is powered off or restarted:\n"),
#     input("Saves changes made to the running configuration to the startup configuration file:\n"),
#     input("The IP address of a router the host uses to connect to remote networks, such as the internet:\n"),
#     input("SVI:\n"),
#     input("Default SVI:\n"),
#     input("What type of interface has no physical port associated with it?\n"),
#     input("Configure an SVI on a switch:\n"),
#     input("What is the blueprint for assigning an IPv4 address to a switch?\n"),
#     input("Which command enables the SVI?\n"),
#     input("What is the blueprint for configuring a default gateway to a switch?\n"),
#     input("What command helps verify switch interfaces?\n"),
#     input("Command can be used to test connectivity to another device on the network or a website on the internet:\n")
# ]
CH4_Q = [
    input("The services and protocols in the TCP/IP suite are defined by which group?\n"),
    input("ISO:\n"),
    input("TIA/EIA:\n"),
    input("ITU:\n"),
    input("ANSI\n"),
    input("IEEE\n"),
    input("The physical layer standards address three functional areas:\n"),
    input('Method of converting a stream of data bits into a predefined "code".\n'),
    input("The capacity at which a medium can carry data:\n"),
    input("Bandwidth is typically measured in:\n"),
    input("Fundamental unit of bandwidth:\n"),
    input("1 Kbps =\n"),
    input("1 Mbps =\n"),
    input("1 Gbps =\n"),
    input("1 Tbps =\n"),
    input("Terms used to measure the quality of bandwidth include:\n"),
    input("Refers to the amount of time, including delays, for data to travel from one given point to another:\n"),
    input("The measure of the transfer of bits across the media over a given period of time; usually lower than the bandwidth:\n"),
    input("The measure of usable data transferred over a given period of time; always lower than throughput:\n"),
    input("\n"),
    input("\n"),
    input("\n"),
]

# CH1_A = [
#     "Intermediary Device",
#     "DSL",
#     "Copper",
#     "Peer-to-Peer",
#     "Internet Corporation for Assigned Names and Numbers",
#     "Satellite",
#     "Intermediary Device",
#     "LAN",
#     "Media",
#     "IP Address",
#     "Wireless",
#     "DSL",
#     "Dial-Up Telephone",
#     "LAN",
#     "Logical Topology Diagram",
#     "End Device",
#     "Intermediary Device",
#     "The Internet",
#     "Internet Architecture Board",
#     "Fiber-Optic",
#     "End Device",
#     "Internet Engineering Task Force",
#     "Topology Diagram",
#     "Digital Subscriber Line",
#     "Dedicated Leased Line",
#     "NIC",
#     "Interface",
#     "QoS",
#     "Extranet",
#     "WAN",
#     "Port",
#     "Physical Topology Diagram",
#     "Symmetric Digital Subscriber Line",
#     "Intranet",
#     "Network Architecture",
#     "Fault Tolerance",
#     "Redundancy",
#     "Packet Switching",
#     "Congestion",
#     "Integrity",
#     "MAC Address",
#     "Physical",
#     "Availability",
#     "Confidentiality",
#     "Cisco Certified Network Administration",
#     "Network Address Translation",
#     "Metro Ethernet",
#     "Fiber Data Distributed Interface",
#     "Denial of Service",
#     "Virtual Private Network",
#     "Firewall",
#     "Zero-Day or Zero-Hour",
#     "Virus, Worm, or Trojan"
# ]
# CH3_A = [
#     "Network Communications Protocols",
#     "Network Security Protocols",
#     "Routing Protocols",
#     "Service Discovery Protocols",
#     "Network Protocol Suites",
#     "Stateless Address Autoconfiguration",
#     "Domain Name System",
#     "DHCPv4",
#     "Stateless Address Autoconfiguration",
#     "Simple Mail Transfer Protocol",
#     "Post Office Protocol 3",
#     "Internet Message Access Protocol",
#     "File Transfer Protocol",
#     "Secure Shell File Transfer Protocol",
#     "Trivial File Transfer Protocol",
#     "Hypertext Transfer Protocol",
#     "Hypertext Transfer Protocol Secure",
#     "Representational State Transfer",
#     "Transmission Control Protocol",
#     "User Datagram Protocol",
#     "IPv4",
#     "IPv6",
#     "Network Address Translation",
#     "ICMPv4",
#     "ICMPv6 ND",
#     "Open Shortest Path First",
#     "Enhanced Interior Gateway Routing Protocol",
#     "Border Gateway Protocol",
#     "Address Resolution Protocol",
#     "Ethernet",
#     "WLAN",
#     "Media Access Control",
#     "Network Interface Card",
#     "Source MAC Address",
#     "Destination MAC Address",
#     "Secure Sockets Layer",
#     "Transport Layer Security",
#     "Quality of Service"
# ]
# CH2_A = [
#     "Shell",
#     "Kernel",
#     "Hardware",
#     "Cisco Internetwork Operating System",
#     "Firmware",
#     "Secure Shell",
#     "Console",
#     "Telnet",
#     "Console",
#     "Telnet/SSH",
#     "Aux",
#     "User EXEC Mode",
#     "Privileged EXEC Mode",
#     ">",
#     "#",
#     "Line Configuration Mode",
#     "Interface Configuration Mode",
#     "hostname",
#     "no hostname",
#     "service password-encryption",
#     "VTY",
#     "line configuration 0",
#     "show running-config",
#     "banner motd",
#     "startup-config",
#     "Flash",
#     "running-config",
#     "copy running-config startup-config",
#     "Default Gateway",
#     "Switch Virtual Interface",
#     "VLAN1",
#     "Switch Virtual Interface",
#     "interface vlan 1",
#     "ip address ip-address subnet-mask",
#     "no shutdown",
#     "ip default-gateway ip-address",
#     "show ip interface brief",
#     "ping"
# ]
CH4_A = [
    "Internet Engineering Task Force",
    "International Organization for Standardization",
    "Telecommunications Industry Association/Electronic Industries Association",
    "International Telecommunication Association",
    "American National Standards Institute",
    "Institute of Electronics and Electronics Engineers",
    "Physical Components, Encoding, Signaling",
    "Encoding",
    "Bandwidth",
    "kbps, Mbps, or Gbps",
    "1 bps",
    "1,000 bps",
    "1,000,000 bps",
    "1,000,000,000 bps",
    "1,000,000,000,000 bps",
    "Latency, Throughput, Goodput",
    "Latency",
    "Throughput",
    "Goodput",
    "",
    "",
    "",
]
